package io.opentracing.contrib.specialagent.common;

public interface BraveConstant {

    /* tracing*/
    String BRAVE_SERVICE_NAME = "BRAVE_SERVICE_NAME";
    String BRAVE_TRACE_ID_128BIT = "BRAVE_TRACE_ID_128BIT";

    /* sender*/
    String BRAVE_SENDER_TYPE = "BRAVE_SENDER_TYPE";
    String BRAVE_SENDER_ADDRESS = "BRAVE_SENDER_ADDRESS";

    /* reporter*/
    String BRAVE_MESSAGE_MAX_BYTES = "BRAVE_MESSAGE_MAX_BYTES";
    String BRAVE_CLOSE_TIMEOUT_NANOS = "BRAVE_CLOSE_TIMEOUT_NANOS";
    String BRAVE_MESSAGE_TIMEOUT_NANOS = "BRAVE_MESSAGE_TIMEOUT_NANOS";
    String BRAVE_QUEUE_MAX_BYTES = "BRAVE_QUEUE_MAX_BYTES";
    String BRAVE_QUEUE_MAX_SPANS = "BRAVE_QUEUE_MAX_SPANS";
    String BRAVE_SPAN_BYTES_ENCODER = "BRAVE_SPAN_BYTES_ENCODER";


    /* sampler*/
    String BRAVE_SAMPLER_TYPE = "BRAVE_SAMPLER_TYPE";
    String BRAVE_SAMPLER_PARAM = "BRAVE_SAMPLER_PARAM";


}
